# Generated by Django 4.0.2 on 2022-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistcandidates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
